### ISSUE TITLE
Can't make this work with flow --

### ISSUE THREAD

**Issue by zettam** [samim23/DeepDreamAnim#10]
`TypeError: Required argument 'flow' (pos 3) not found`

I have cv2 installed -- any ideas?

**Comment by zettam** [comment]
`python dreamer.py --input myvideo --output myvideo/frames -flow 1` this is what I run

**Comment by zettam** [comment]
And the full error is as follows 

```
Traceback (most recent call last):
  File "dreamer.py", line 341, in <module>
    args.zoom, args.stepsize, args.blend, args.layers, args.guide, args.gpu, args.flow)
  File "dreamer.py", line 236, in main
    iterations=3, poly_n=5, poly_sigma=1.2, flags=0)
TypeError: Required argument 'flow' (pos 3) not found
```

**Comment by zettam** [comment]
Works with opencv 2.4.11 - does not work with newer releases (windows 8.1 64bit with Anaconda)

**Comment by aertist** [comment]
I have this same issue. Can someone help?
