### ISSUE TITLE
Flow behaves additive

### ISSUE THREAD

**Issue by zettam** [samim23/DeepDreamAnim#11]
When flow is enabled, specially for sequences where frames are similar (slow or no camera movement, partial/slow pixel movement) every frame becomes additive. Is this the normal behavior ?

When flow is turned off, everything seems okay over a long period of time (but there is a lot of jitter for sure) but when flow is on it becomes brighter and brighter every frame unless the changes between frames are too clear.

**Comment by samim23** [comment]
this is a problem of how openCV handles flow - if you find a fix please send a pull request
