### ISSUE TITLE
Processing frames in random order

### ISSUE THREAD

**Issue by tkoham** [samim23/DeepDreamAnim#14]
When I run the image processing pass, the script seems to pull random frames from the frame directory instead of processing them sequentially:

Frame 158 of 1866
Frame Time: 1s
Estimated Total Time Remaining: 1708s (0:28:28)
***************************************
Processing: myvideo/**image-000659.png**
0 0 inception_3b/output (360, 540, 3)
0 1 inception_3b/output (360, 540, 3)
...
3 9 inception_3b/output (360, 540, 3)
***************************************
Saving Image As: myvideo/frames/**frame_000159.png**

this gives me an unwatchable mess when I try to re-stitch the frames.

**Comment by HandsomeDevilv112** [comment]
I'm having this happen to me on ubuntu as well, this is not happening on the version of this I have working on windows, which has been there for some time. 
I thought it was somehow possible to be my file format at first, but changing it did not fix the issue. 
I'm using "python dreamer.py --input ddin --output ddout"

**Comment by ChoclateRain** [comment]
I too am having this issue with the frames coming out in a random order, does anyone know python and can figure out whats going wrong in the code?
--ChocolateRain

**Comment by ChoclateRain** [comment]
@tkoham After some time i found a fixed version of this, i cant seem to find the bookmark (It was on github) so heres the fixed dreamer.py (just take out the .txt obvs)


[dreamer.py.txt](https://github.com/samim23/DeepDreamAnim/files/1075982/dreamer.py.txt)

**Comment by HandsomeDevilv112** [comment]
Finally got around to checking that. Thanks ChocolateRain! Worked like a charm!

**Comment by tkoham** [comment]
thanks!

**Comment by ghost** [comment]
hey im having trouble inputing my frames it keep trowing me this:
```
[image2 @ 000002644de424e0] Could find no file with path 'C:\Users\root\Desktop\unamed\frames\/frame_%6d.png' and index in the range 0-4
C:\Users\root\Desktop\unamed\frames\/frame_%6d.png: No such file or directory
```

**Comment by kthordarson** [comment]
Easy fix.

Find line 156:
idinput = os.listdir(inputdir)

Replace with:
vidinput = sorted(os.listdir(inputdir))

**Comment by tkoham** [comment]
Thanks! can't believe I missed that
