### ISSUE TITLE
Get an error towards the end of the script  IndexError: list index out of range

### ISSUE THREAD

**Issue by darkwraithcovenant** [samim23/DeepDreamAnim#3]
I am a bit new to this, but when I ran it, it would run through the inception layers just fine how it normally would, towards the last few lines I got the following error.
Traceback (most recent call last):
  File "dreamer.py", line 254, in <module>
    main(args.input, args.output, args.preview, args.octaves, args.octavescale, args.iterations, args.jitter, args.zoom,
 args.stepsize, args.blend, args.layers)
  File "dreamer.py", line 169, in main
    img = PIL.Image.open(inputdir+'/'+vids[0])
IndexError: list index out of range

**Comment by samim23** [comment]
Will push a new version of the animator end of week. fixing this bug and adding optical flow and guided dreaming. This bug is ignorable, it just a sloppy mistake how your very last frame is handled.

**Comment by samim23** [comment]
This bug has been resolved by v.1.1
