### ISSUE TITLE
Stitching

### ISSUE THREAD

**Issue by Acanterelle** [samim23/DeepDreamAnim#4]
Hi. After some installation experimentation, I've managed to get all the dependencies installed under Windows 7: Anaconda, FFmpeg, CUDA, CudNN, Caffe, + all the addons etc required. I've accomplished this following tutorials which are now linked on new wiki page in the DeepDreamAnim wiki.

So far so  good. I stuck the dreamer.py file in the same parent directory as caffe and have managed to get through clipping up the volcano using: 

C:\deepdream\DreamAnim>python dreamer.py -i C:\frames -o C:\frames_out

and then successfully dreampt onto those frames after swapping the places of the frames to new folders with:

C:\deepdream\DreamAnim>python dreamer.py -i C:\frames -o C:\frames_out

However, the last step generates an error message:

---

[image2 @ 0000000002f9f5c0] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
C:\frames_out/*.jpeg: Function not implemented

---

This really won't be an issue in terms of generating videos for me, as I'm quite comfortable using _myfavoritesoftware_ to do the stitching (like Blender).

Is this something in the dreamer.py or simply something to do with running this under Windows?

Warm Regards!

M

P.S. Great Job!

**Comment by samim23** [comment]
Your supplied path is incorrect.
try something like:

C:\deepdream\DreamAnim>python dreamer.py -i C:\deepdream\DreamAnim\myvideo\frames -o C:\deepdream\DreamAnim\myvideo\framesout

**Comment by Acanterelle** [comment]
I put the frames directory in C:\frames. It's not a typo. I can try moving the frames directory into a deep dream parent directory but that just means more character entry...

Why would splitting work with that directory but not joining? It's not like the .py script or files have moved...

Thanks for replying!

**Comment by samim23** [comment]
Try it with the path structure i suggested, it should work just fine. I´m not to familiar with how windows deals with paths, but you might want to try local paths anyhow, e.g. \myvideo\frames instead of the entire C:.... .
