### ISSUE TITLE
guide image issues

### ISSUE THREAD

**Issue by muchogrande** [samim23/DeepDreamAnim#9]
Hi, thanks for the excellent script - I've got it working fine except that when I try to set a guide image this error is thrown:

  File "dreamer.py", line 21, in preprocess
    return np.float32(np.rollaxis(img, 2)[::-1]) - net.transformer.mean['data']
ValueError: operands could not be broadcast together with shapes (4,301,600) (3,1,1) 

I've tried a variety of .png images (even trying one of the source images) but I get this error every time.

**Comment by samim23** [comment]
This could be caused by a few things: Wrong Image format / wrong resolution / image alpha channel.
Experiment with those, hopefully you´ll get it to work

**Comment by muchogrande** [comment]
Thanks. So I assume the guide image must be PNG, no transparency, same resolution as the source image seq that I am processing. Correct?

Also, is there a danger in aborting the script and re-running it? I have been doing that while testing and am finding that it appears some args get stuck in memory. EG: even though I removed the guide arg the script was still searching out the guide image and throwing the error.
